version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  OPEN_JDK_URL: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08/OpenJDK8U-jdk_x64_windows_hotspot_8u242b08.zip
  OPEN_JDK_DIR: jdk8u242-b08
  OPENJFX_REPO: http://hg.openjdk.java.net/openjfx/8u-dev/rt
  OPENJFX_TAG: 8u60-b27
  WINSDK_DIR: C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A
  VS150COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
  MSVC_VER: 14.16.27023
  VisualStudioVersion: 15.0
install:
- cmd: dir "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC"
- cmd: dir %APPVEYOR_BUILD_FOLDER%
- cmd: curl -L -o jdk.zip %OPEN_JDK_URL%
- cmd: 7z x jdk.zip
- cmd: set JAVA_HOME=%APPVEYOR_BUILD_FOLDER%\%OPEN_JDK_DIR%
- cmd:  PATH %JAVA_HOME%\bin;%PATH%
- cmd:  echo "PATH:%PATH%"
- cmd:  java -version
- cmd:  set WORK_DIR=work
- cmd:  hg clone %OPENJFX_REPO% %WORK_DIR%
- cmd:  cd "%WORK_DIR%"
- cmd:  hg up %OPENJFX_TAG%
- cmd:  set JDKJFX=%OPEN_JDK_DIR%-with-jfx%OPENJFX_TAG%
build_script:
- cmd: dir %cd%
- cmd: echo "Patching build.gradle to allow parsing the version string provided by OpenJDK 8"
- ps: (Get-Content -path build.gradle -Raw) -replace 'v\.indexOf\(" \(build "\)', 'v.indexOf("(build ")' | Set-Content -path build.gradle
- ps: (Get-Content -path build.gradle -Raw) -replace 'v\.substring\(ib \+ 8', 'v.substring(ib + 7' | Set-Content -path build.gradle
- cmd: copy %APPVEYOR_BUILD_FOLDER%\gradlew.bat %APPVEYOR_BUILD_FOLDER%\%WORK_DIR%\gradlew.bat
- cmd: dir %APPVEYOR_BUILD_FOLDER%\%WORK_DIR%
- cmd: echo "running gradle in %cd%"
- cmd: gradle
- cmd: md %JDKJFX%
- cmd: xcopy %APPVEYOR_BUILD_FOLDER%\%OPEN_JDK_DIR% %JDKJFX%\%JDKJFX% /i /e /k /h
- cmd: xcopy %APPVEYOR_BUILD_FOLDER%\%WORK_DIR%\build\sdk\rt %JDKJFX%\%JDKJFX%\jre /i /e /k /h
artifacts:
- path: /$(WORK_DIR)/build/sdk
  name: openjfx-sdk-$(OPENJFX_TAG)
- path: /$(WORK_DIR)/$(JDKJFX)
  name: $(JDKJFX)
deploy:
- provider: GitHub
  release: openjfx-v$(OPENJFX_TAG)
  description: OpenJFX $(OPENJFX_TAG) binaries for Windows
  auth_token:
    secure: Nmp14mBBSCsz0TDpfQMkk+nf2lwkE9SF9S0zvcSy80gP+x/HF4X8ErV7XyIf1vTB
  artifact: openjfx-sdk-$(OPENJFX_TAG),$(JDKJFX)
  force_update: true
  on:
    branch: master
